[workspace]
    resolver        = "2"
    members         = ["aoc-2024", "aoc-2021", "utils", "macros"]
    default-members = ["aoc-2024"]
    default-run     = "aoc-2024"

    [workspace.package]
        edition = "2021"
        authors = ["Ian Pratt <ianjdpratt@gmail.com"]
