[workspace]
    resolver        = "2"
    members         = ["utils", "2024", "macros"]
    default_members = ["2024"]

    [workspace.package]
        edition = "2021"
        authors = ["Ian Pratt <ianjdpratt@gmail.com"]
