[package]
    name              = "utils"
    version           = "0.1.0"
    authors.workspace = true
    edition.workspace = true

[dependencies]
    macros     = { path = "../macros" }
    itertools  = "^0.13.0"
    anyhow     = "^1.0.9"
    num-traits = "^0.2.19"
